export const PaginationDefaults = {
  DEFAULT_NEWS_LIMIT: 10,
  DEFAULT_RECENT_ITEMS_LIMIT: 10,
  DEFAULT_RECENT_GRADES_LIMIT: 5,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  MIN_PAGE_SIZE: 1,
} as const;
