export const ValidationLimits = {
  USER_NAME_MIN_LENGTH: 2,
  USER_NAME_MAX_LENGTH: 100,
  GRADE_MIN_SCORE: 0,
  GRADE_MAX_SCORE: 100,
  GRADE_FEEDBACK_MAX_LENGTH: 1000,
  ANNOUNCEMENT_TITLE_MIN_LENGTH: 5,
  ANNOUNCEMENT_TITLE_MAX_LENGTH: 200,
  ANNOUNCEMENT_CONTENT_MIN_LENGTH: 10,
  ANNOUNCEMENT_CONTENT_MAX_LENGTH: 5000,
  ERROR_MESSAGE_MIN_LENGTH: 1,
  ERROR_MESSAGE_MAX_LENGTH: 1000,
  USER_AGENT_MAX_LENGTH: 500,
  ERROR_SOURCE_MAX_LENGTH: 100,
} as const;

export const StatusCodeRanges = {
  SUCCESS_MIN: 200,
  SUCCESS_MAX: 300,
  CLIENT_ERROR_MIN: 400,
} as const;
