export { StudentDashboardService } from './StudentDashboardService';
export { TeacherService } from './TeacherService';
export { GradeService } from './GradeService';
export { UserService } from './UserService';
export { ParentDashboardService } from './ParentDashboardService';
export { CommonDataService } from './CommonDataService';
export { AnnouncementService } from './AnnouncementService';
export { getRoleSpecificFields } from '../type-guards';
export { getUniqueIds, buildEntityMap, fetchAndMap } from './EntityMapUtils';
export type { EntityWithId } from './EntityMapUtils';
