export const ValidationLimits = {
  USER_NAME_MIN_LENGTH: 2,
  USER_NAME_MAX_LENGTH: 100,
  GRADE_MIN_SCORE: 0,
  GRADE_MAX_SCORE: 100,
  GRADE_FEEDBACK_MAX_LENGTH: 1000,
  ANNOUNCEMENT_TITLE_MIN_LENGTH: 5,
  ANNOUNCEMENT_TITLE_MAX_LENGTH: 200,
  ANNOUNCEMENT_CONTENT_MIN_LENGTH: 10,
  ANNOUNCEMENT_CONTENT_MAX_LENGTH: 5000,
  ERROR_MESSAGE_MIN_LENGTH: 1,
  ERROR_MESSAGE_MAX_LENGTH: 1000,
  USER_AGENT_MAX_LENGTH: 500,
  ERROR_SOURCE_MAX_LENGTH: 100,
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 128,
  PHONE_MIN_LENGTH: 10,
  PHONE_MAX_LENGTH: 13,
  NISN_LENGTH: 10,
  MESSAGE_SUBJECT_MIN_LENGTH: 1,
  MESSAGE_SUBJECT_MAX_LENGTH: 200,
  MESSAGE_CONTENT_MIN_LENGTH: 1,
  MESSAGE_CONTENT_MAX_LENGTH: 10000,
} as const

export const UserRoleValues = {
  STUDENT: 'student',
  TEACHER: 'teacher',
  PARENT: 'parent',
  ADMIN: 'admin',
} as const

export const AnnouncementTargetRoles = {
  ...UserRoleValues,
  ALL: 'all',
} as const

export const StatusCodeRanges = {
  SUCCESS_MIN: 200,
  SUCCESS_MAX: 300,
  CLIENT_ERROR_MIN: 400,
} as const

export const GradeThresholds = {
  A: 90,
  B: 80,
  C: 70,
  D: 60,
  E: 50,
  PASSING_SCORE: 60,
  PRECISION_FACTOR: 10,
} as const

export const GRADE_A_THRESHOLD = GradeThresholds.A

export const GRADE_B_THRESHOLD = GradeThresholds.B

export const GRADE_C_THRESHOLD = GradeThresholds.C

export const GRADE_D_THRESHOLD = GradeThresholds.D

export const GRADE_E_THRESHOLD = GradeThresholds.E

export const PASSING_SCORE_THRESHOLD = GradeThresholds.PASSING_SCORE

export const GRADE_PRECISION_FACTOR = GradeThresholds.PRECISION_FACTOR

export const RETRY_CONFIG = {
  DEFAULT_MAX_RETRIES: 3,
  DEFAULT_BASE_DELAY_MS: 1000,
  DEFAULT_JITTER_MS: 0,
  MAX_DELAY_MS: 30000,
} as const

export const AVATAR_BASE_URL = 'https://i.pravatar.cc/150'

export const getAvatarUrl = (userId: string): string => {
  return `${AVATAR_BASE_URL}?u=${encodeURIComponent(userId)}`
}

export const getCurrentTimestamp = (): string => new Date().toISOString()

export const getCurrentTimestampMs = (): number => Date.now()

export const addMilliseconds = (timestamp: number, ms: number): string => {
  return new Date(timestamp + ms).toISOString()
}

export const HttpStatusCode = {
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
} as const
